---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - split.smi-spec.io
  resources:
  - trafficsplits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - split.smi-spec.io
  resources:
  - trafficsplits/finalizers
  verbs:
  - update
- apiGroups:
  - split.smi-spec.io
  resources:
  - trafficsplits/status
  verbs:
  - get
  - patch
  - update
